name: frontend_ui
description: "Best 3 Deals App"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  http: ^1.3.0
  sqflite: 2.3.3+2
  path: ^1.9.0
  geolocator: 12.0.0
  geocoding: ^3.0.0
  shared_preferences: 2.5.2
  url_launcher: ^6.3.1
  google_maps_flutter: ^2.10.0
  image_picker: ^1.1.2
  firebase_core: ^2.0.0
  firebase_messaging: ^14.0.0
  flutter_local_notifications: ^17.2.1
  provider: ^6.1.2
  carousel_slider: 5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg
    - assets/default_avatar.jpg
    - assets/promos/image1.png
    - assets/promos/image2.jpg
    - assets/promos/image3.png

flutter_native_splash:
  color: "#ffffff"               # Background color (match your Flutter splash)
  image: assets/logo.jpg         # Path to your logo
  android: true                  # Enable Android splash screen
  ios: true                      # Enable iOS splash screen
  android_12:
    image: assets/logo.jpg       # Android 12+ logo
    icon_background_color: "#ffffff"
    color: "#ffffff"
